### ISSUE TITLE
list and table views do not show (sub)tasks if the parent task is in anothe project

### ISSUE THREAD

**Issue by avatar1024** [go-vikunja/vikunja#782]
### Description

If I move subtask from the project where the parent task is to another project, the subtask appears in the kaban and gantt views of that other project but not in the list or table view. It however still (usefully) remains in the list and table view of the original project where the parent task is.

I would expect (and it would be good) that the task appear in all views of the project it has been moved to (but I'd say it makes sense if it also stays in the list view of the project the parent task is).

For more on the topic of small inconsistencies I encountered in Vikunja in the logic and managements of the hierarchy between project/subprojects/tasks/subtasks, I finally found the time to write a little piece here: https://community.vikunja.io/t/improvement-suggestions/3732.

### Vikunja Version

0.24.6

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![Image](https://github.com/user-attachments/assets/b6f495ea-dde6-4732-8285-8764e4d77b38)
![Image](https://github.com/user-attachments/assets/34368176-fb11-489c-a884-4926d8003f2b)
![Image](https://github.com/user-attachments/assets/d6178232-7e23-4e67-b367-255f92f2f5ed)
![Image](https://github.com/user-attachments/assets/549a6637-eb10-40fa-abf6-d4487692db21)

**Comment by kolaente** [comment]
Do you see this only with subtasks or with no-related tasks as well?

**Comment by avatar1024** [comment]
> Do you see this only with subtasks or with no-related tasks as well?

I can this happening only where there is a Parent-Subtask relation. I tried other relations and I can see no issues there. I reckon this is because only the Parent-Subtask relation has an impact on the list view, where the subtask is showed with an indent below the parent tasks in the list view of the project where the parent task lives.

When moving a subtask in another project, the in the list view of the project where the parent task lives, the subtask appears showing the name of the other project. I reckon the best would actually be to see exactly the same (both parent and subtask) int he list view of the project where the subtask lives, but this time showing the parent task with the name of the project it lives in.

**Comment by kolaente** [comment]
Maybe fixed in https://github.com/go-vikunja/vikunja/pull/1000, please check with the next unstable build (should be ready for deployment in ~30min, also on [try](https://try.vikunja.io)).

**Comment by lithiumsulfate** [comment]
I think this is still (partially) happening in 1.0.0-rc2 (reproducible in the current demo site as well). If there are two tasks -- one in Project A and one in Project B -- and I assign the Project B task as a subtask of the one in Project A, the now-subtask will suddenly disappear from the List view of Project B (but it does still show in the Table and Kanban views of Project B). 

This happens to deeper nested levels as well; the complete task tree is properly shown in the List view of the project with the highest level parent task, but none of the other project(s) List view(s) show any of the subtasks any longer.

**Comment by kolaente** [comment]
@lithiumsulfate I've pushed another fix for this in https://github.com/go-vikunja/vikunja/issues/782, please check with the next unstable build (should be ready for deployment in ~30min, also on [try](https://try.vikunja.io)).

**Comment by lithiumsulfate** [comment]
@kolaente looks good now as far as I can tell, thanks for the quick response!
